version: '3.2'
services:
  consul:
    image: consul:${TAG:-latest}
    network_mode: "host"
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    command: agent -dns-port=53 -recursor=8.8.8.8 -ui -server -bind=${BOOT2DCOS_HOST} -client=${BOOT2DCOS_HOST} -bootstrap-expect=1 -domain boot2dcos -datacenter ${BOOT2DCOS_DATACENTER_NAME}
    volumes: 
      - ./consul/config:/consul/config
    dns: ${BOOT2DCOS_HOST}
  proxy:
    image: traefik:1.6
    command: --web --logLevel=INFO
    networks:
      - webgateway
    ports:
      - "81:80"
      - "8085:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/boot2dcos-lb.toml:/etc/traefik/traefik.toml
    dns: ${BOOT2DCOS_HOST}
    depends_on: 
      - consul
  registrator:
    image: gliderlabs/registrator:latest
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    dns: ${BOOT2DCOS_HOST}
    command: "-ip ${BOOT2DCOS_HOST} consul://consul.service.boot2dcos:8500"
    restart: always
    depends_on: 
     - consul
  #core:
  #  image: boot2dcos/core
  #  dns: ${BOOT2DCOS_HOST}
  #  ports:
  #    - "8080:8080" 
  #  environment:
  #    - BOOT2DCOS_HOST=${BOOT2DCOS_HOST}
  #  depends_on: 
  #    - consul
  #genconf:
  #  image: boot2dcos/genconf:1.10.0
  #  dns: ${BOOT2DCOS_HOST}
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  depends_on: 
  #    - consul
#volumes:
#  genconf:
#     driver_opts:
#        type: none
#        device: ${BOOT2DCOS_HOME}/baremetal/dcos/genconf #NOTE needs full path (~ doesn't work)
#        o: bind